# Generated by Django 2.2.4 on 2019-08-25 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteID', models.CharField(max_length=20, verbose_name='地點代碼')),
                ('siteDesc', models.CharField(max_length=120, verbose_name='位址說明')),
                ('siteCity', models.CharField(blank=True, choices=[('Tpe', '台北市'), ('NewTpe', '新北市'), ('Tauyan', '桃園市'), ('Taichong', '台中市'), ('Kaohsung', '高雄市')], default='Tpe', max_length=10, verbose_name='城市')),
            ],
            options={
                'verbose_name': '安裝地點',
                'verbose_name_plural': '安裝地點',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('sendTime', models.DateTimeField(auto_now_add=True)),
                ('toWhom', models.CharField(max_length=30)),
                ('isMail', models.BooleanField(default=False)),
                ('isLine', models.BooleanField(default=False)),
                ('isELK', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '訊息傳送Ｌog',
                'verbose_name_plural': '訊息傳送Ｌog',
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standID', models.CharField(max_length=20, verbose_name='機台代碼')),
                ('standDesc', models.CharField(max_length=120, null=True, verbose_name='機台說明')),
                ('standPrice', models.FloatField(default=0, verbose_name='機台價格')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameSite.Location', verbose_name='安裝地點')),
            ],
            options={
                'verbose_name': '機台',
                'verbose_name_plural': '機台',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(default=160)),
                ('male', models.BooleanField(default=False)),
                ('website', models.URLField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='不願意透漏身份的人', max_length=10)),
                ('message', models.TextField()),
                ('del_pass', models.CharField(max_length=10)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameSite.Mood')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDay', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('amount', models.FloatField(default=0, verbose_name='金額')),
                ('note', models.TextField(verbose_name='備註說明')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
                ('standID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameSite.Stand', verbose_name='機台代碼')),
            ],
            options={
                'verbose_name': '機台收入',
                'verbose_name_plural': '機台收入',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('note', models.TextField()),
                ('ddate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
