# Generated by Django 2.2.4 on 2019-08-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0002_incomes_site_stand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incomes',
        ),
    ]
