# Generated by Django 2.2.4 on 2019-08-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0004_delete_stand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
