# Generated by Django 2.2.4 on 2019-08-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0005_delete_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteID', models.CharField(max_length=20, verbose_name='地點代碼')),
                ('siteDesc', models.CharField(max_length=120, verbose_name='位址說明')),
                ('siteCity', models.CharField(blank=True, choices=[('Tpe', '台北市'), ('NewTpe', '新北市'), ('Tauyan', '桃園市'), ('Taichong', '台中市'), ('Kaohsung', '高雄市')], default='Tpe', max_length=10, verbose_name='城市')),
            ],
            options={
                'verbose_name': '安裝地點',
                'verbose_name_plural': '安裝地點',
            },
        ),
    ]
