# Generated by Django 2.2.4 on 2019-08-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0006_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='siteCity',
        ),
    ]
