# Generated by Django 2.2.4 on 2019-08-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0007_remove_location_sitecity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Loc', 'verbose_name_plural': 'Loc'},
        ),
        migrations.AddField(
            model_name='location',
            name='siteCity',
            field=models.CharField(blank=True, choices=[('Tpe', '台北市'), ('NewTpe', '新北市'), ('Tauyan', '桃園市'), ('Taichong', '台中市'), ('Kaohsung', '高雄市')], default='Tpe', max_length=10, verbose_name='城市'),
        ),
    ]
