# Generated by Django 2.2.4 on 2019-08-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0009_auto_20190821_0635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Site',
        ),
    ]
