# Generated by Django 2.2.4 on 2019-08-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0011_auto_20190821_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '安裝地點', 'verbose_name_plural': '安裝地點'},
        ),
    ]
