# Generated by Django 2.2.4 on 2019-08-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0013_incomes_stand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '地點', 'verbose_name_plural': '地點'},
        ),
    ]
