# Generated by Django 2.2.4 on 2019-08-20 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0014_auto_20190821_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='location',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '安裝地點', 'verbose_name_plural': '安裝地點'},
        ),
        migrations.DeleteModel(
            name='Incomes',
        ),
        migrations.DeleteModel(
            name='Stand',
        ),
    ]
