# Generated by Django 2.2.4 on 2019-08-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0020_incomes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stand',
            options={'verbose_name': 'AAA', 'verbose_name_plural': 'AAA'},
        ),
    ]
