# Generated by Django 2.2.4 on 2019-08-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0021_auto_20190821_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stand',
            options={'verbose_name': '機台', 'verbose_name_plural': '機台'},
        ),
    ]
