# Generated by Django 2.2.4 on 2019-08-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0022_auto_20190821_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='standDesc',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='standPrice',
        ),
    ]
