# Generated by Django 2.2.4 on 2019-08-20 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameSite', '0023_auto_20190821_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='負責人'),
        ),
        migrations.AddField(
            model_name='stand',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameSite.Location', verbose_name='安裝地點'),
        ),
        migrations.AddField(
            model_name='stand',
            name='standDesc',
            field=models.CharField(max_length=120, null=True, verbose_name='機台說明'),
        ),
        migrations.AddField(
            model_name='stand',
            name='standPrice',
            field=models.FloatField(default=0, verbose_name='機台價格'),
        ),
    ]
