# Generated by Django 2.2.4 on 2019-08-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0024_auto_20190821_0708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incomes',
        ),
    ]
