# Generated by Django 2.2.4 on 2019-08-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0025_delete_incomes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stand',
        ),
    ]
