# Generated by Django 2.2.4 on 2019-08-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0027_stand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stand',
            options={},
        ),
    ]
