# Generated by Django 2.2.4 on 2019-08-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0032_incomes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incomes',
        ),
    ]
