# Generated by Django 2.2.4 on 2019-08-21 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0034_incomes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomes',
            options={},
        ),
    ]
