# Generated by Django 2.2.4 on 2019-08-21 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0035_auto_20190821_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomes',
            options={'verbose_name': '機台收入', 'verbose_name_plural': '機台收入'},
        ),
    ]
