# Generated by Django 2.2.4 on 2019-08-21 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameSite', '0036_auto_20190821_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDay', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('amount', models.FloatField(default=0, verbose_name='金額')),
                ('note', models.TextField(verbose_name='備註說明')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
                ('standID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameSite.Stand', verbose_name='機台代碼')),
            ],
            options={
                'verbose_name': '機台收入',
                'verbose_name_plural': '機台收入',
            },
        ),
        migrations.DeleteModel(
            name='Incomes',
        ),
    ]
