# Generated by Django 2.2.4 on 2019-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0037_auto_20190822_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('sendTime', models.DateTimeField(auto_now=True)),
                ('toWhom', models.CharField(max_length=30)),
                ('isMail', models.BooleanField(default=False)),
                ('isLine', models.BooleanField(default=False)),
                ('isELK', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '訊息傳送Ｌog',
                'verbose_name_plural': '訊息傳送Ｌog',
            },
        ),
    ]
