# Generated by Django 2.2.4 on 2019-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0038_messagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='sendTime',
            field=models.DateTimeField(),
        ),
    ]
