# Generated by Django 2.2.4 on 2019-08-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0040_auto_20190824_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='isELK',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='isLine',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='isMail',
            field=models.BooleanField(),
        ),
    ]
