# Generated by Django 2.2.4 on 2019-08-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameSite', '0041_auto_20190824_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='isELK',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='isLine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='isMail',
            field=models.BooleanField(default=False),
        ),
    ]
